version: '3.8'

services:
  # The Database
  postgres:
    image: postgis/postgis:14-3.2
    container_name: tat_sahayk_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=oceandb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # The Cache
  redis:
    image: redis:7-alpine
    container_name: tat_sahayk_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
